version: "3.9"
services:
  scraper-back:
    build:
      dockerfile: ./Dockerfile
    hostname: scraper-back
    ports:
      - "8080:8080"
    environment:
      - DB_URL=
      - DB_USR=
      - DB_PWD=
    networks:
      - common-network

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - common-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - common-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/docker/volumes/grafana-storage:/var/lib/grafana
    networks:
      - common-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    user: "$UID:$GID"
    depends_on:
      - prometheus

networks:
  common-network:
    driver: bridge