global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scraper-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'node_prometheus'
    static_configs:
      - targets: ['localhost:9090','localhost:9100']
