spring:
  application:
    name: ScraperApi
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver