server:
  servlet:
    context-path: /scrape/api
spring:
  application:
    name: ScraperApi
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: scraper-hikari-pool

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


scrape:
  cron-job-generation-rate-ms: ${CRON_JOB_GENERATION_TIME_MS:600000}
  is-giga-chat-enabled: true
  model:
    summary-url: ${SUMMARY_MODEL_URL:http://89.169.143.232:8000/publication/summary}